version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "mysql"
    environment:
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - db-data:/foo

volumes:
  db-data:
